### ISSUE TITLE
 @conda-forge-admin, please rerender

### ISSUE THREAD

**Issue by bgruening** [conda-forge/r-captioner-feedstock#5]
Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by bgruening** [comment]
@conda-forge-admin, please rerender

**Comment by dbast** [comment]
Solved via https://github.com/conda-forge/r-captioner-feedstock/pull/6

**Comment by bgruening** [comment]
Thanks, but I'm wondering why the bot has not catched that up.

Thanks for the fix.

**Comment by dbast** [comment]
Seems to work right now this morning ... https://github.com/conda-forge/r-captioner-feedstock/issues/7 https://github.com/conda-forge/r-captioner-feedstock/issues/8
